Hometask 6
KuznetsovaAS/hometask_1 pull request #10
Opened 2019-11-23 10:19 UTC by KuznetsovaAS

My sixth hometask.

2019-11-26 17:35 UTC, illarionovEA requested changes
с алгоритмом что-то не так. Видно по графику, что после 200 шага количество вершин уперлось в 25 и не меняется. Так быть не должно. Мы должны наблюдать процесс блуждания по разным состояниям.

2019-11-27 12:52 UTC, KuznetsovaAS commented
Исправила

2019-11-27 14:21 UTC, illarionovEA commented
новая схема вновь не будет сходиться к равномерному и ответ получается завышенным

2019-12-01 08:38 UTC, KuznetsovaAS commented
Функция переделана

2019-12-06 15:47 UTC, illarionovEA approved these changes

2019-12-06 16:08 UTC, merged