Hometask 7
KuznetsovaAS/hometask_1 pull request #11
Opened 2019-12-08 08:01 UTC by KuznetsovaAS

My seventh homework

2019-12-08 08:55 UTC, illarionovEA requested changes
темы топиков пока еще слабо сформированы. Обрати внимание на комментарии к лекции в группе. Уменьшение словаря позволит ускорить время на интерацию и приведет к более осмысленному результату

2019-12-09 16:33 UTC, KuznetsovaAS commented
Полученный результат с уменьшенным словарем

2019-12-15 11:15 UTC, KuznetsovaAS commented
Я уменьшила размер словаря, чтобы результат получился лучше

2019-12-15 18:12 UTC, illarionovEA commented
темы по-прежнему не интерпретируюся, нужно пробовать подбирать параметры

2019-12-17 15:22 UTC, KuznetsovaAS commented
Изменила значения параметров, теперь темы выделяются значительно лучше

2019-12-19 20:55 UTC, illarionovEA commented
не могу с этим согласиться, приведи примеры тем, которые ты выделяешь

2019-12-20 09:36 UTC, KuznetsovaAS commented
Из полученных топиков я могу выделить следующие темы:
Topics 1,3,13 - computer, computer science
Topic 5 - publication
Topic 6 - motorcycle, motorcyclist
Topic 7 - marriage
Topic 8 - electronic equipment
Topic 10 - public event/show
Topic 11 - television, celebrities
Topic 14 - cars
Topic 15 - service center
Topic 19 - developments in electronics
Topic 20 - the law SOX

2019-12-20 09:42 UTC, KuznetsovaAS commented
А мне ведь не нужно ничего делать на сайте codewars.com? Или нужно?

2019-12-20 10:11 UTC, illarionovEA commented
нужно добиться лучшего проявления тем, пока не могу согласиться (из 10 слов только 2-3 как-то относятся к теме, это мало, из оставшихся слов можно придумать другую тему). Нужно попробовать другие параметры, например, для априорных распределений. Чтобы итерации были не такими долгими, код можно оптимизировать. Например, вместо выражений вида ```Nkw[z[i]][word[i]]``` правильнее писать ```Nkw[z[i], word[i]]```, это ускорит раза в 2.

2019-12-20 10:16 UTC, illarionovEA commented
еще в 2 раза быстрее будет, если сделать ```z_i = z[i]``` и всюду подставлять ```z_i```, а не обращаться к массивам

2019-12-21 08:38 UTC, KuznetsovaAS commented
Теперь точно темы интерпретируются гораздо лучше. И в каждом топике все слова однозначно относятся к теме топика.

2019-12-21 08:39 UTC, KuznetsovaAS commented
Ссылка на мой профиль в codewars.com
https://www.codewars.com/users/KuznetsovaAS

2019-12-21 09:18 UTC, illarionovEA approved these changes

2019-12-21 10:21 UTC, merged

2020-02-06 08:22 UTC, illarionovEA commented
Перешли мне, пожалуйста, любой свой контакт по которому с тобой можно связаться. Сообщения вк у тебя ограничены.

2020-02-06 11:57 UTC, KuznetsovaAS commented
Добрый день.Я открыла сообщения вк.--Отправлено из мобильной Яндекс.Почты06.02.2020, 11:23, "illarionovEA" <notifications@github.com>:Перешли мне, пожалуйста, любой свой контакт по которому с тобой можно связаться. Сообщения вк у тебя ограничены.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.