Hometask 2
KuznetsovaAS/hometask_1 pull request #6
Opened 2019-09-30 19:07 UTC by KuznetsovaAS

My second homework

2019-10-01 14:16 UTC, illarionovEA requested changes
задание 6 нужно оформить в виде функции, которая работает с данными любой размерности и любым числом кластеров.

2019-10-02 21:49 UTC, KuznetsovaAS commented
Исправлена функция k-means

2019-10-13 15:09 UTC, illarionovEA commented
функции ```k-means``` как таковой нет
в функции ```get_labels``` происходит что-то очень странное и по форме, и по содержанию
перед применением  ```k-means``` данные рекомендуется нормализовать

2019-10-13 20:00 UTC, KuznetsovaAS commented
Подправлен алгоритм k-means в соответствии с указанными замечаниями

2019-10-26 15:24 UTC, KuznetsovaAS commented
Подправлен алгоритм k-means в соответствии с указанными замечаниями

2019-10-26 15:43 UTC, KuznetsovaAS commented
Подправлен алгоритм k-means в соответствии с указанными замечаниями

2019-11-09 19:52 UTC, illarionovEA approved these changes

2019-11-10 10:26 UTC, merged