Hometask 3
KuznetsovaAS/hometask_1 pull request #7
Opened 2019-10-11 21:06 UTC by KuznetsovaAS

My third homework

2019-10-13 12:42 UTC, illarionovEA requested changes
```python
for i in range(k):
        for j in range(i+1, k):
            if (res[i]==res[j]):
```
перепиши в более компактное выражение без двойных циклов и ```if```

2019-10-13 12:44 UTC, illarionovEA commented
при вливании этого PR в мастер из мастера будет удален hometask_1.ipynb, так не должно быть

2019-10-13 21:15 UTC, KuznetsovaAS commented
Исправлены замечания

2019-10-14 16:40 UTC, illarionovEA approved these changes

2019-10-26 15:31 UTC, merged