Hometask 5
KuznetsovaAS/hometask_1 pull request #9
Opened 2019-11-08 19:58 UTC by KuznetsovaAS

My fifth homework.

2019-11-09 19:41 UTC, illarionovEA requested changes
случайное блуждание с требуемыми свойствами генерируется в 6 строчек кода

откуда получились эти числа?
ksi = np.sqrt(7)/2*x+y/2+3
eta = 2*y+6

как появился арккосинус при генерации распределения в круге?

2019-11-10 16:55 UTC, KuznetsovaAS commented
В файле исправлены задания, о которых Вы упоминали в комментарии.

2019-11-17 10:05 UTC, illarionovEA commented
арккосинус - это неверное преобразование для радиуса
со случайным блужданием что-то не то. длина пути должна быть ровно 100 (начало и конец в 0)

2019-11-17 16:30 UTC, KuznetsovaAS commented
Переделана функция равномерного распределения в круге и случайное блуждание.

2019-11-18 20:46 UTC, illarionovEA commented
давай разберем
```python
def walk(xmass, ymass, n):
    while (len(xmass)-1)!=n:
        xmass = [0, np.sqrt(1/2)*np.random.choice([-1,1])]
        ymass = [0, np.sqrt(1/2)*np.random.choice([-1,1])]
        while (xmass[len(xmass)-1]**2+ymass[len(ymass)-1]**2)>eps and (len(xmass)-1)<=n:
            xmass.append(xmass[len(xmass)-1]+np.sqrt(1/2)*np.random.choice([-1,1]))
            ymass.append(ymass[len(ymass)-1]+np.sqrt(1/2)*np.random.choice([-1,1]))
    xx = np.array(xmass)
    ymass = np.array(ymass)
    xmass = xx*math.cos(-pi/4)-ymass*math.sin(-pi/4)
    ymass = xx*math.sin(-pi/4)+ymass*math.cos(-pi/4)
```
Функция берет на вход xmass ymass и внутри себя заново их инициализирует, это нехорошо и ни к чему. На вход достаточно n.

```(xmass[len(xmass)-1]**2+ymass[len(ymass)-1]**2)>eps``` - согласно этому условию процесс завершится при первом возвращении в ноль. Это неверно, мы можем сколько угодно раз возвращаться в ноль. главное вернуться на последнем шаге.

```xmass[len(xmass)-1]```  пишется проще: ```xmass[-1]```
 
```*math.sin(-pi/4)``` - лучше поделить на корень 2, чем дергать 4 раза тригоноветрические функции

генерить случаные шаги в цикле долго и дорого, правильнее использовать параметр ```size``` у функции ```np.random.choice``` чтобы получить выборку нужного объема

перепиши функцию по следующей логике:
1) выбираем n/2 номеров шагов, на которых идем в +1
2) заполняем массив длины n значениями +1 и -1
3) поворотом переходим в новую систему координат

это дожно занять ровно 6 строчек кода

2019-11-19 19:06 UTC, KuznetsovaAS commented
Функция генерации случайного блуждания переписана в соответствии с описанной логикой.

2019-11-22 16:06 UTC, illarionovEA approved these changes

2019-11-23 08:48 UTC, merged